### ISSUE TITLE
LCD4 patch

### ISSUE THREAD

**Issue by yundddd** [beagleboard/meta-beagleboard#10]
The LCD4 cape basic support patch uses P9_21 in bone_lcd4_cape_keys_00A2_pins pin group. However, according to the schematic file at Beagleboardtoys wiki, it doesn't use P9_21. This error prevents any other virtual capes such as UART2 or SPI0 to be loaded because of pin conflict on P9_21.

Patch location:
meta-beagleboard / common-bsp / recipes-kernel / linux / linux-mainline-3.8 / not-capebus / 0168-capes-add-basic-support-for-LCD4-capes.patch

Schematic file of LCD4:
https://github.com/CircuitCo/BeagleBone-LCD4-RevA1/blob/master/BeagleBone-LCD4-RevA1-schematic.pdf?raw=true

**Comment by koenkooi** [comment]
That's an issue with https://github.com/beagleboard/kernel/tree/3.8 not this repo.
